spark.master                     spark://spark-master:7077
spark.executor.memory            2g
spark.driver.memory              2g
spark.sql.parquet.compression.codec  snappy
spark.hadoop.fs.gs.impl          com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem
spark.hadoop.google.cloud.auth.service.account.enable  true
