FROM python:3.11-slim

WORKDIR /app

COPY ml_model_packaging_service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ml_training_service/ ./ml_training_service/
COPY ml_evaluation_pipeline/ ./ml_evaluation_pipeline/
COPY ml_model_packaging_service/api/ ./ml_model_packaging_service/api/

CMD ["uvicorn", "ml_model_packaging_service.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
